
CREATE TABLE INFORMATION_SCHEMA.SECU_USERS (
	USER_ID INTEGER DEFAULT NEXT VALUE FOR "INFORMATION_SCHEMA"."SYSTEM_SEQUENCE_9FCAE26E_25BF_4FA6_8680_4C67B851161E" NOT NULL AUTO_INCREMENT,
	PROF_ID INTEGER NOT NULL,
	USER_LOGIN VARCHAR(100) NOT NULL,
	USER_PASSWORD VARCHAR(100) NOT NULL,
	CONSTRAINT SECU_USERS_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_6 ON INFORMATION_SCHEMA.SECU_USERS (USER_ID);
CREATE INDEX SECU_USERS_FK_INDEX_6 ON INFORMATION_SCHEMA.SECU_USERS (PROF_ID);

ALTER TABLE INFORMATION_SCHEMA.SECU_USERS ADD CONSTRAINT SECU_USERS_FK FOREIGN KEY (PROF_ID) REFERENCES INFORMATION_SCHEMA.ORMA_PROFESSIONAL(PROF_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;




CREATE TABLE INFORMATION_SCHEMA.ORMA_PROFESSIONAL (
	PROF_ID INTEGER DEFAULT NEXT VALUE FOR "INFORMATION_SCHEMA"."SYSTEM_SEQUENCE_A1F377C9_96AC_4637_9D51_D1B0AC7891B8" NOT NULL AUTO_INCREMENT,
	PROF_NAME VARCHAR(50) NOT NULL,
	PROF_SURNAME_1 VARCHAR(50),
	PROF_SURNAME_2 VARCHAR(50),
	PROF_ID_VALUE VARCHAR(100) NOT NULL,
	CONSTRAINT ORMA_PROFESSIONAL_PK PRIMARY KEY (PROF_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_C ON INFORMATION_SCHEMA.ORMA_PROFESSIONAL (PROF_ID);
